// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `FormsConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=SF26;initial catalog=FormBuilder;connect timeout=3600;user id=sa;password=sa1`
//     Include Views:          `True`

using System;
using LambdaSqlBuilder;
using DapperExtensions.Mapper;

namespace GreatfulPatient.DAL.Entities
{
    /// <summary>
    /// A class which represents the Forms table.
    /// </summary>
	
	[SqlLamTable(Name = "[dbo].[Forms]")]
	public partial class Forms
	{
			public virtual int ID { get; set; }
		public virtual string FormName { get; set; }
		public virtual string json { get; set; }
	}



    /// <summary>
    /// A class which represents the Forms table.
    /// </summary>
	
	
	public sealed class FormsMapper : ClassMapper<Forms>
	{
		public FormsMapper()
		{
			Schema("dbo");
            Table("Forms");
						Map(f => f.ID).Key(KeyType.Identity);
		
					Map(f => f.FormName).Column("FormName");
	
					Map(f => f.json).Column("json");
	
	
		}
	}
}



//#########################################


	
	




